package com.kamsiob.steadyhealth.session

import com.kamsiob.steadyhealth.domain.AbilityDomain
import com.kamsiob.steadyhealth.domain.Exclusion
import com.kamsiob.steadyhealth.domain.GettingAround

/**
 * The library. Everything the app can ever ask somebody to do.
 *
 * Written out as data rather than generated, in the order a session uses them: warm
 * ups, then the main movements grouped by ability, then cool downs. ADDENDUM-03 Part
 * 4 promises "sixty or so movements" and there are seventy seven, because the
 * number is not the same in the four versions of the app: somebody on their feet
 * sees fifty of them, a wheelchair user thirty five, somebody in bed thirty one.
 * No screen prints any of those numbers, for the reason says_library gives.
 *
 * Every setup line is one sentence somebody can follow with the phone face down on a
 * table, because that is how the audio reads them out. Every stop rule is a
 * permission rather than a warning: "Stop whenever" and not "do not overdo it".
 *
 * This is four libraries in one list, and [Movement.ways] is what separates them.
 * Nothing here is the on-feet version with something taken out: a movement belongs to
 * a way when its setup line can be followed exactly as written by somebody who gets
 * around that way, and where the sentence would have to change to suit another body
 * that is a second movement with its own id and its own words. Wheeling is Go rather
 * than a smaller kind of walking, and none of these words tells anybody that the
 * version they are reading is the lesser one.
 *
 * The strings are here rather than in resources for the same reason the ladders were:
 * this file is meant to be read as a whole. They move to resources with the
 * translations, which is Phase 8.
 */
@Suppress("LargeClass") // A library of seventy odd movements. It is a table, not logic.
object Movements {

    private val feet = setOf(GettingAround.OnFeet, GettingAround.Walker)
    private val seated = setOf(GettingAround.Wheelchair)
    private val bed = setOf(GettingAround.InBed)
    private val everyone = GettingAround.entries.toSet()

    /** Standing up or sitting in a wheelchair, but not from a bed. */
    private val feetOrSeated = feet + seated

    /** The two ways done from a seat: a wheelchair, or a bed and a chair. */
    private val seatedOrBed = seated + bed

    // --- Warm ups. Sixty to ninety seconds, no targets that matter. -----------

    val warmUps: List<Movement> = listOf(
        Movement(
            id = "warm_march",
            name = "Marching on the spot",
            setup = "Stand tall, hold something if you like, and march gently on the spot.",
            stopRule = "Stop whenever you like.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Go,
            area = Area.Hip,
            kit = setOf(Kit.None),
            startTarget = 30,
            ways = feet,
            seconds = 30,
        ),
        Movement(
            id = "warm_shoulder_rolls",
            name = "Shoulder rolls",
            setup = "Roll your shoulders slowly backwards. Big, easy circles.",
            stopRule = "Small circles are fine.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 20,
            ways = everyone,
            seconds = 20,
        ),
        Movement(
            id = "warm_ankle_circles",
            name = "Ankle circles",
            setup = "Hold something, lift one foot, and circle the ankle. Then the other.",
            stopRule = "Stop whenever you like.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 20,
            ways = feet,
            seconds = 20,
        ),
        Movement(
            id = "warm_side_reach",
            name = "Reaching side to side",
            setup = "Reach one arm up and over, gently. Then the other side.",
            stopRule = "Only as far as is comfortable.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Steady,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 20,
            ways = everyone,
            excludedBy = setOf(Exclusion.LiftingOverhead),
            seconds = 20,
        ),
        Movement(
            id = "warm_heel_toe",
            name = "Heel and toe",
            setup = "Hold the counter. Rock forward onto your toes, back onto your heels.",
            stopRule = "Small movements count.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 25,
            ways = feet,
            seconds = 25,
        ),
        Movement(
            id = "warm_seated_march",
            name = "Seated marching",
            setup = "Sit tall and march your knees up, one at a time.",
            stopRule = "As high as is comfortable.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Go,
            area = Area.Hip,
            // Somewhere to sit, which is not the question O5 asks. That one is
            // about a sturdy chair without arms to stand up from, and answering
            // no to it used to take this away from somebody already sitting in a
            // wheelchair, along with the two below.
            kit = setOf(Kit.None),
            startTarget = 30,
            ways = everyone,
            seconds = 30,
        ),
        Movement(
            id = "warm_seated_ankles",
            name = "Seated ankle circles",
            setup = "Feet flat, lift one heel and circle the ankle slowly. Then the other.",
            stopRule = "Small circles are fine.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 20,
            ways = seated,
            seconds = 20,
        ),
        Movement(
            id = "warm_arm_circles",
            name = "Arm circles",
            setup = "Arms out to the side, small circles forward, then back the other way.",
            stopRule = "Smaller circles count.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 20,
            ways = feetOrSeated,
            seconds = 20,
        ),
        Movement(
            id = "warm_easy_pushes",
            name = "Easy pushes",
            setup = "A few easy pushes on the rims, no hurry, to get the arms going.",
            stopRule = "Stop whenever you like.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Go,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 30,
            ways = seated,
            seconds = 30,
        ),
        Movement(
            id = "warm_hands",
            name = "Opening and closing the hands",
            setup = "Spread your fingers wide, then make a soft fist. Both hands, slowly.",
            stopRule = "Stop whenever you like.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Carry,
            area = Area.Arm,
            kit = setOf(Kit.None),
            startTarget = 20,
            ways = seatedOrBed,
            seconds = 20,
        ),
        Movement(
            id = "warm_knee_rolls",
            name = "Knee rolls",
            setup = "Knees bent, roll both knees gently to one side, then the other.",
            stopRule = "Only as far as is comfortable.",
            counted = Counted.Hold,
            piece = Piece.WarmUp,
            domain = AbilityDomain.Steady,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 30,
            ways = bed,
            excludedBy = setOf(Exclusion.TwistingBack),
            seconds = 30,
        ),
    )

    // --- Get up. Chairs, floors, and everything between. ----------------------

    val getUp: List<Movement> = listOf(
        Movement(
            id = "sit_to_stand_high",
            name = "Stands from a high seat",
            setup = "Use a high chair or the edge of the bed. Stand up, sit down.",
            stopRule = "Use your hands if you need them. That still counts.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Chair),
            startTarget = 5,
            ceiling = 12,
            harder = "sit_to_stand",
            ways = feet,
            sensedBy = Sensed.Stands,
        ),
        Movement(
            id = "sit_to_stand",
            name = "Chair stands",
            setup = "Chair against a wall, arms crossed, feet flat. Stand up, sit down.",
            stopRule = "Use your hands whenever you need to.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Chair),
            startTarget = 8,
            ceiling = 20,
            easier = "sit_to_stand_high",
            harder = "sit_to_stand_slow",
            ways = feet,
            excludedBy = setOf(Exclusion.DeepKneeBending),
            sensedBy = Sensed.Stands,
        ),
        Movement(
            id = "sit_to_stand_slow",
            name = "Slow chair stands",
            setup = "Same chair. Take three seconds to sit down each time.",
            stopRule = "Faster is fine if three seconds is too long.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Chair),
            startTarget = 6,
            ceiling = 15,
            easier = "sit_to_stand",
            harder = "sit_to_stand_one_arm",
            ways = feet,
            excludedBy = setOf(Exclusion.DeepKneeBending),
            seconds = 60,
            sensedBy = Sensed.Stands,
        ),
        Movement(
            id = "sit_to_stand_one_arm",
            name = "Chair stands, one hand",
            setup = "Same chair, one hand on your chest, one free if you need it.",
            stopRule = "Both hands whenever you want them.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Chair),
            startTarget = 6,
            ceiling = 15,
            easier = "sit_to_stand_slow",
            ways = feet,
            excludedBy = setOf(Exclusion.DeepKneeBending),
            sensedBy = Sensed.Stands,
        ),
        Movement(
            id = "mini_squat",
            name = "Mini squats",
            setup = "Chair behind you. Sit back until you touch it, then stand.",
            stopRule = "Go only as far down as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Chair),
            startTarget = 8,
            ceiling = 16,
            easier = "sit_to_stand",
            ways = feet,
            excludedBy = setOf(Exclusion.DeepKneeBending),
        ),
        Movement(
            id = "step_up_low",
            name = "Step ups",
            setup = "One low step, near a rail. Up with one foot, then the other, then down.",
            stopRule = "Hold the rail the whole time if you like.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Step),
            startTarget = 8,
            ceiling = 20,
            harder = "step_up_high",
            ways = feet,
            excludedBy = setOf(Exclusion.Impact),
        ),
        Movement(
            id = "step_up_high",
            name = "Step ups, higher step",
            setup = "A higher step, near a rail. Same movement, more of a lift.",
            stopRule = "Back to the low step whenever you want.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Step),
            startTarget = 8,
            ceiling = 20,
            easier = "step_up_low",
            ways = feet,
            excludedBy = setOf(Exclusion.Impact),
        ),
        Movement(
            id = "half_kneel_to_stand",
            name = "Half kneel to stand",
            setup = "One knee down, hand on a chair, drive up through the front foot.",
            stopRule = "Use both hands. Take as long as you like.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Chair, Kit.Floor),
            startTarget = 4,
            ceiling = 10,
            harder = "floor_to_stand",
            ways = feet,
            excludedBy = setOf(Exclusion.GettingOnTheFloor, Exclusion.DeepKneeBending),
            seconds = 60,
        ),
        Movement(
            id = "floor_to_stand",
            name = "Floor to stand",
            setup = "Down through a side sit, and back up the same way. Chair beside you.",
            stopRule = "Hands, knees, furniture, whatever gets you up.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.Floor, Kit.Chair),
            startTarget = 3,
            ceiling = 8,
            easier = "half_kneel_to_stand",
            ways = feet,
            excludedBy = setOf(Exclusion.GettingOnTheFloor),
            seconds = 90,
        ),
        Movement(
            id = "glute_bridge",
            name = "Bridges",
            setup = "On your back, knees bent, lift your hips, lower slowly.",
            stopRule = "Small lifts count.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Hip,
            kit = setOf(Kit.Floor),
            startTarget = 8,
            ceiling = 20,
            ways = feet,
            excludedBy = setOf(Exclusion.LyingFlat, Exclusion.GettingOnTheFloor),
        ),
        Movement(
            id = "seated_forward_lean",
            name = "Forward lean and back",
            setup = "Sitting tall, lean forward over your knees, pause, come back up.",
            stopRule = "Only as far as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 20,
            ways = everyone,
            excludedBy = setOf(Exclusion.DeepForwardBending),
        ),
        Movement(
            id = "pressure_relief_lift",
            name = "Lifts from the armrests",
            setup = "Hands on the armrests, lift clear for a few seconds, down with control.",
            stopRule = "A small lift counts.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Shoulder,
            // The chair somebody is sitting in is not something the room might be
            // missing, so these ask for nothing rather than for a sturdy chair.
            kit = setOf(Kit.None),
            startTarget = 5,
            ceiling = 15,
            ways = seated,
        ),
        Movement(
            id = "transfer_practice",
            name = "Transfers",
            setup = "Chair to bed and back, however you do it. Rest between.",
            stopRule = "Two is a session. Stop whenever.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 4,
            ceiling = 10,
            ways = seated,
            seconds = 90,
        ),
        Movement(
            id = "sit_to_edge",
            name = "Sitting up to the edge",
            setup = "Roll onto your side, push up with the lower arm. Rest there.",
            stopRule = "Rest as long as you need between.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 3,
            ceiling = 8,
            ways = bed,
            seconds = 60,
            sensedBy = Sensed.Stands,
        ),
        Movement(
            id = "pressure_relief_lean",
            name = "Leaning to one side",
            setup = "Hook one arm over the backrest and lean well over that side, then back.",
            stopRule = "A small lean counts.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 4,
            ceiling = 12,
            ways = seated,
            seconds = 60,
        ),
        Movement(
            id = "seat_shuffle",
            name = "Shuffling in the seat",
            setup = "Hands on the frame, shift your hips forward in the seat, then back.",
            stopRule = "Small shifts count.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Hip,
            kit = setOf(Kit.None),
            startTarget = 6,
            ceiling = 16,
            ways = seated,
            seconds = 45,
        ),
        Movement(
            id = "bed_bridge",
            name = "Bridges in bed",
            setup = "On your back, knees bent and feet down, lift your hips, then lower them.",
            stopRule = "Small lifts count.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Hip,
            kit = setOf(Kit.None),
            startTarget = 6,
            ceiling = 20,
            ways = bed,
            excludedBy = setOf(Exclusion.LyingFlat),
            seconds = 45,
        ),
        Movement(
            id = "bed_roll",
            name = "Rolling onto your side",
            setup = "Knees bent, and roll your shoulders and hips together onto one side.",
            stopRule = "Rest as long as you like between.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 4,
            ceiling = 12,
            ways = bed,
            seconds = 60,
        ),
        Movement(
            id = "bed_to_chair",
            name = "Bed to the chair",
            setup = "Sit up to the edge, then across to the chair beside you, however you do it.",
            stopRule = "Rest as long as you need, and stop whenever.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.GetUp,
            area = Area.Shoulder,
            kit = setOf(Kit.Chair),
            startTarget = 2,
            ceiling = 8,
            ways = bed,
            seconds = 90,
        ),
    )

    // --- Go. Walking, stairs, stepping, breathing. -----------------------------

    val go: List<Movement> = listOf(
        Movement(
            id = "walk",
            name = "A walk",
            setup = "At a pace you could talk right through. Out and back is fine.",
            stopRule = "Turn round whenever you like. It still counts.",
            counted = Counted.Minutes,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Knee,
            kit = setOf(Kit.None),
            startTarget = 2,
            ceiling = 30,
            harder = "walk_brisk",
            ways = feet,
            seconds = 120,
        ),
        Movement(
            id = "walk_brisk",
            name = "A brisk walk",
            setup = "Quick enough that talking takes a bit of effort. Not out of breath.",
            stopRule = "Slow down whenever. That still counts.",
            counted = Counted.Minutes,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Knee,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 45,
            easier = "walk",
            ways = feet,
            excludedBy = setOf(Exclusion.Impact),
            seconds = 600,
        ),
        Movement(
            id = "step_in_place",
            name = "Stepping on the spot",
            setup = "Phone in your pocket. March on the spot, knee to halfway up your thigh.",
            stopRule = "Lower knees are fine. Stop whenever.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Hip,
            kit = setOf(Kit.None),
            startTarget = 40,
            ceiling = 120,
            ways = feet,
            seconds = 60,
            sensedBy = Sensed.Steps,
        ),
        Movement(
            id = "stairs",
            name = "Stairs",
            setup = "One flight, holding the rail. Up, turn round, and back down.",
            stopRule = "Stop on the landing whenever you want.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Knee,
            kit = setOf(Kit.Step),
            startTarget = 1,
            ceiling = 4,
            ways = feet,
            excludedBy = setOf(Exclusion.Impact),
            seconds = 60,
        ),
        Movement(
            id = "wheeling",
            name = "Wheeling",
            setup = "At a pace you could talk right through. A flat, clear stretch.",
            stopRule = "Stop whenever you like.",
            counted = Counted.Minutes,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 2,
            ceiling = 30,
            ways = seated,
            seconds = 120,
        ),
        Movement(
            id = "slow_breaths",
            name = "Slow breaths",
            setup = "In through the nose, out slowly. Tap once each time you breathe out.",
            stopRule = "Never hold your breath.",
            counted = Counted.Taps,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.None,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 20,
            ways = everyone,
            seconds = 60,
        ),
        Movement(
            id = "heel_slides",
            name = "Heel slides",
            setup = "One heel at a time, up towards you and back down.",
            stopRule = "As far as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Knee,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 24,
            ways = bed,
        ),
        Movement(
            id = "wheeling_bursts",
            name = "Quicker pushes",
            setup = "Push a little quicker for a minute, then settle back to your own pace.",
            stopRule = "Ease off whenever you like.",
            counted = Counted.Minutes,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 1,
            ceiling = 6,
            ways = seated,
            seconds = 60,
        ),
        Movement(
            id = "seated_punches",
            name = "Punching out",
            setup = "Arms out in front, one then the other, at a pace you could keep up.",
            stopRule = "Slow down whenever you like.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 20,
            ceiling = 60,
            ways = seated,
            seconds = 60,
        ),
        Movement(
            id = "bed_marching",
            name = "Marching lying down",
            setup = "On your back, knees bent, lift one knee then the other, like marching.",
            stopRule = "Small lifts count. Stop whenever.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Hip,
            kit = setOf(Kit.None),
            startTarget = 16,
            ceiling = 40,
            ways = bed,
            excludedBy = setOf(Exclusion.LyingFlat),
            seconds = 60,
        ),
        Movement(
            id = "breathing_arms",
            name = "Breathing with your arms",
            setup = "Breathe in as your arms come out to the side, out as they come down.",
            stopRule = "Never hold your breath.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Go,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 8,
            ceiling = 20,
            ways = bed,
            seconds = 45,
        ),
    )

    // --- Carry. Pushing, pulling, holding. ------------------------------------

    val carry: List<Movement> = listOf(
        Movement(
            id = "wall_push_up",
            name = "Wall push ups",
            setup = "Hands on the wall at chest height, body in one line. Breathe out as you push.",
            stopRule = "Step closer to the wall to make it easier.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.Wall),
            startTarget = 8,
            ceiling = 20,
            harder = "counter_push_up",
            ways = feet,
            excludedBy = setOf(Exclusion.Pushing),
        ),
        Movement(
            id = "counter_push_up",
            name = "Counter push ups",
            setup = "Hands on a kitchen counter. Body stays in one line.",
            stopRule = "Back to the wall whenever you want.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 8,
            ceiling = 20,
            easier = "wall_push_up",
            harder = "incline_push_up",
            ways = feet,
            excludedBy = setOf(Exclusion.Pushing),
        ),
        Movement(
            id = "incline_push_up",
            name = "Low incline push ups",
            setup = "Hands on a low step or a sturdy chair. Body in one line.",
            stopRule = "Higher hands whenever you want.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.Step),
            startTarget = 6,
            ceiling = 15,
            easier = "counter_push_up",
            ways = feet,
            excludedBy = setOf(Exclusion.Pushing),
        ),
        Movement(
            id = "band_row",
            name = "Band rows",
            setup = "Band round your feet or a table leg. Pull back, breathe out as you pull.",
            stopRule = "Less stretch on the band makes it easier.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.Band),
            startTarget = 8,
            ceiling = 20,
            ways = everyone,
        ),
        Movement(
            id = "band_press",
            name = "Band press",
            setup = "Band behind you, press forward at chest height. Breathe out as you press.",
            stopRule = "Less stretch on the band makes it easier.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.Band),
            startTarget = 8,
            ceiling = 20,
            ways = everyone,
            // Somebody who left pushing out means pressing too, whatever they are
            // sitting in. LOGIC.md section 5 offers this as the replacement for the
            // pushing ladder, which is a different question from whether the app may
            // put a press in a session for somebody who asked for no pressing.
            excludedBy = setOf(Exclusion.Pushing),
        ),
        Movement(
            id = "carry_walk",
            name = "Carrying something",
            setup = "A bag of shopping in each hand, or one in both. Walk the hallway and back.",
            stopRule = "Put it down whenever you like.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.Weights),
            startTarget = 2,
            ceiling = 8,
            ways = feet,
            seconds = 90,
        ),
        Movement(
            id = "towel_squeeze",
            name = "Towel squeeze",
            setup = "As hard as is comfortable. Five seconds, then let go.",
            stopRule = "Breathe normally the whole time.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Arm,
            kit = setOf(Kit.None),
            startTarget = 6,
            ceiling = 15,
            ways = everyone,
        ),
        Movement(
            id = "overhead_reach",
            name = "Overhead reach",
            setup = "Reach both arms up as far as is comfortable. Slowly.",
            stopRule = "Only as high as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 20,
            ways = everyone,
            excludedBy = setOf(Exclusion.LiftingOverhead),
        ),
        Movement(
            id = "arm_press_overhead",
            name = "Pressing overhead",
            setup = "Hands at your shoulders, press both arms up as far as is comfortable.",
            stopRule = "Only as high as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 8,
            ceiling = 20,
            ways = everyone,
            excludedBy = setOf(Exclusion.LiftingOverhead, Exclusion.Pushing),
            seconds = 45,
        ),
        Movement(
            id = "palm_press",
            name = "Palm press",
            setup = "Hands together in front of you, press your palms together, then ease off.",
            stopRule = "Breathe normally the whole time.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 6,
            ceiling = 15,
            ways = everyone,
            excludedBy = setOf(Exclusion.Pushing, Exclusion.BreathHolding),
            seconds = 45,
        ),
        Movement(
            id = "side_raises",
            name = "Arms out to the side",
            setup = "Arms down by your sides, lift them out to shoulder height, then lower.",
            stopRule = "Only as high as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 8,
            ceiling = 20,
            ways = feetOrSeated,
            seconds = 45,
        ),
        Movement(
            id = "bottle_curls",
            name = "Bottle curls",
            setup = "A full bottle in each hand, bend your elbows up, then lower them slowly.",
            stopRule = "One bottle at a time is fine.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Carry,
            area = Area.Arm,
            kit = setOf(Kit.Weights),
            startTarget = 8,
            ceiling = 20,
            ways = seatedOrBed,
            seconds = 45,
        ),
    )

    // --- Steady. Balance, as a skill. -----------------------------------------

    val steady: List<Movement> = listOf(
        Movement(
            id = "feet_together",
            name = "Feet together",
            setup = "Near a wall or counter. Feet touching, stand still.",
            stopRule = "Touch the counter whenever you need to.",
            counted = Counted.Hold,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 30,
            harder = "semi_tandem",
            ways = feet,
        ),
        Movement(
            id = "semi_tandem",
            name = "Semi-tandem stand",
            setup = "Near a wall or counter. One foot half in front of the other.",
            stopRule = "Hand on the counter whenever you want.",
            counted = Counted.Hold,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 30,
            easier = "feet_together",
            harder = "tandem",
            ways = feet,
        ),
        Movement(
            id = "tandem",
            name = "Tandem stand",
            setup = "Near a wall or counter. Heel right in front of the other toe.",
            stopRule = "Hand on the counter whenever you want.",
            counted = Counted.Hold,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 30,
            easier = "semi_tandem",
            harder = "one_leg",
            ways = feet,
        ),
        Movement(
            id = "one_leg",
            name = "One foot",
            setup = "Near a wall or counter, hand ready. One foot off the ground.",
            stopRule = "Put it down whenever. That is the number.",
            counted = Counted.Hold,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 45,
            easier = "tandem",
            harder = "one_leg_head_turns",
            ways = feet,
        ),
        Movement(
            id = "one_leg_head_turns",
            name = "One foot, looking around",
            setup = "Near a wall or counter. Turn your head slowly, left and right.",
            stopRule = "Stop turning, or put the foot down, whenever.",
            counted = Counted.Hold,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Neck,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 30,
            easier = "one_leg",
            ways = feet,
        ),
        Movement(
            id = "heel_raises",
            name = "Heel raises",
            setup = "Hold a counter. Rise onto your toes, lower slowly.",
            stopRule = "Small rises count.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 25,
            ways = feet,
        ),
        Movement(
            id = "heel_toe_walk",
            name = "Heel to toe walking",
            setup = "Along a counter. Heel right in front of the other toe, step by step.",
            stopRule = "Hold on the whole way if you like.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 8,
            ceiling = 20,
            ways = feet,
        ),
        Movement(
            id = "seated_balance",
            name = "Sitting unsupported",
            setup = "Sitting tall, hands off. Brakes on.",
            stopRule = "Hold on whenever you need to.",
            counted = Counted.Hold,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 20,
            ceiling = 90,
            harder = "seated_balance_eyes_closed",
            ways = seated,
        ),
        Movement(
            id = "ankle_pumps",
            name = "Ankle pumps",
            setup = "Point and flex. One side then the other. Keeps the blood moving.",
            stopRule = "Stop if you get any cramp.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.None),
            startTarget = 20,
            ceiling = 40,
            ways = everyone,
        ),
        Movement(
            id = "seated_rotation",
            name = "Turning to look behind",
            setup = "Hands on your chest. Turn slowly one way, then the other.",
            stopRule = "Only as far as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 8,
            ceiling = 20,
            ways = everyone,
            excludedBy = setOf(Exclusion.TwistingBack),
        ),
        Movement(
            id = "seated_reach_across",
            name = "Reaching across",
            setup = "Brakes on. Reach across your body past the far wheel, then come back.",
            stopRule = "Only as far as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 6,
            ceiling = 16,
            ways = seated,
            excludedBy = setOf(Exclusion.TwistingBack),
            seconds = 45,
        ),
        Movement(
            id = "seated_head_turns",
            name = "Looking around",
            setup = "Sitting tall, turn your head slowly to one shoulder, then to the other.",
            stopRule = "Only as far as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Neck,
            kit = setOf(Kit.None),
            startTarget = 8,
            ceiling = 20,
            ways = seatedOrBed,
            seconds = 45,
        ),
        Movement(
            id = "seated_balance_eyes_closed",
            name = "Sitting unsupported with eyes closed",
            setup = "Brakes on, sitting tall, hands off, and close your eyes.",
            stopRule = "Open your eyes or hold on whenever you want.",
            counted = Counted.Hold,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 10,
            ceiling = 45,
            easier = "seated_balance",
            ways = seated,
            seconds = 45,
        ),
        Movement(
            id = "sit_unsupported_edge",
            name = "Sitting on the edge",
            setup = "Sitting on the edge of the bed, feet down, and let go with both hands.",
            stopRule = "Hold on whenever you need to.",
            counted = Counted.Hold,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 15,
            ceiling = 60,
            ways = bed,
            seconds = 45,
        ),
        Movement(
            id = "edge_reach",
            name = "Reaching from the edge",
            setup = "Sitting on the edge of the bed, reach out to one side, then come back.",
            stopRule = "Only as far as is comfortable.",
            counted = Counted.Reps,
            piece = Piece.Main,
            domain = AbilityDomain.Steady,
            area = Area.Back,
            kit = setOf(Kit.None),
            startTarget = 6,
            ceiling = 16,
            ways = bed,
            seconds = 45,
        ),
    )

    // --- Cool downs. Sixty seconds and two stretches. --------------------------

    val coolDowns: List<Movement> = listOf(
        Movement(
            id = "cool_walk",
            name = "Easy walking",
            setup = "Wander about at whatever pace suits. Let your breathing settle.",
            stopRule = "Sit down whenever you like.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.Go,
            area = Area.None,
            kit = setOf(Kit.None),
            startTarget = 60,
            ways = feet,
            seconds = 60,
        ),
        Movement(
            id = "cool_calf_stretch",
            name = "Calf stretch",
            setup = "Hands on the wall, one foot back, heel down. Hold.",
            stopRule = "Ease off whenever. A stretch never has to hurt.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.Steady,
            area = Area.Ankle,
            kit = setOf(Kit.Wall),
            startTarget = 30,
            ways = feet,
            seconds = 30,
        ),
        Movement(
            id = "cool_chest_stretch",
            name = "Chest stretch",
            setup = "Hands behind you, or one arm on a doorframe. Open across the front.",
            stopRule = "Ease off whenever.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 30,
            ways = everyone,
            seconds = 30,
        ),
        Movement(
            id = "cool_seated_breathing",
            name = "Sitting and breathing",
            setup = "Sit or lie comfortably. In through the nose, out slowly. Let it settle.",
            stopRule = "Never hold your breath.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.Go,
            area = Area.None,
            kit = setOf(Kit.None),
            startTarget = 60,
            ways = everyone,
            seconds = 60,
        ),
        Movement(
            id = "cool_thigh_stretch",
            name = "Thigh stretch",
            setup = "Hold the counter. Heel towards your bottom, knee pointing down.",
            stopRule = "Ease off whenever. A strap or a towel helps.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.GetUp,
            area = Area.Knee,
            kit = setOf(Kit.None),
            startTarget = 30,
            ways = feet,
            seconds = 30,
        ),
        Movement(
            id = "cool_neck_stretch",
            name = "Neck stretch",
            setup = "Drop one ear towards your shoulder and rest there. Then the other side.",
            stopRule = "Ease off whenever.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.Steady,
            area = Area.Neck,
            kit = setOf(Kit.None),
            startTarget = 30,
            ways = everyone,
            seconds = 30,
        ),
        Movement(
            id = "cool_shoulder_stretch",
            name = "Shoulder stretch",
            setup = "One arm across your chest, held gently in place with the other. Then swap.",
            stopRule = "Ease off whenever.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.Carry,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 30,
            ways = everyone,
            seconds = 30,
        ),
        Movement(
            id = "cool_easy_wheeling",
            name = "Easy wheeling",
            setup = "Wheel slowly about at whatever pace suits. Let your breathing settle.",
            stopRule = "Stop whenever you like.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.Go,
            area = Area.Shoulder,
            kit = setOf(Kit.None),
            startTarget = 60,
            ways = seated,
            seconds = 60,
        ),
        Movement(
            id = "cool_lying_still",
            name = "Lying and breathing",
            setup = "Lie back, arms by your sides. In through the nose, out slowly.",
            stopRule = "Never hold your breath.",
            counted = Counted.Hold,
            piece = Piece.CoolDown,
            domain = AbilityDomain.Go,
            area = Area.None,
            kit = setOf(Kit.None),
            startTarget = 60,
            ways = bed,
            seconds = 60,
        ),
    )

    val all: List<Movement> = warmUps + getUp + go + carry + steady + coolDowns

    fun byId(id: String): Movement? = all.firstOrNull { it.id == id }

    /**
     * Everything this person could be offered, before a session is planned.
     *
     * Four filters, in the order they matter: the way they get around, what they said
     * to leave out, what is in the room, and any area they said hurts.
     */
    /**
     * What the very first session opens with.
     *
     * Named rather than derived. O4 is a designed moment: it has to need nothing in
     * the room, be over in about two minutes, and look like something rather than
     * like a warm up. A rule that picked "the shortest available movement" would get
     * one of those three right.
     */
    fun first(way: GettingAround): Movement? = byId(
        when (way) {
            GettingAround.OnFeet, GettingAround.Walker -> "heel_raises"
            GettingAround.Wheelchair -> "overhead_reach"
            GettingAround.InBed -> "sit_to_edge"
        },
    )

    fun available(
        way: GettingAround,
        exclusions: Set<Exclusion> = emptySet(),
        kit: Set<Kit> = setOf(Kit.None, Kit.Chair, Kit.Wall),
        sore: Set<Area> = emptySet(),
    ): List<Movement> = all.filter { movement ->
        way in movement.ways &&
            movement.excludedBy.none { it in exclusions } &&
            movement.kit.all { it == Kit.None || it in kit } &&
            movement.area !in sore
    }
}
